# Generated by Django 5.0.6 on 2024-08-02 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('status', models.BooleanField(default=False, help_text='Используйте для включения/выключения сотрудника.', verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('strike', models.IntegerField(default=0, verbose_name='Штрафные баллы')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено в')),
                ('level', models.CharField(choices=[('junior', 'junior'), ('middle', 'middle'), ('senior', 'senior')], default='junior', max_length=10, verbose_name='Уровень')),
                ('position', models.CharField(choices=[('copywriter', 'Копирайтер'), ('mobilograph', 'Мобилограф'), ('editor', 'Монтажер'), ('designer', 'Дизайнер'), ('smm', 'СММ'), ('marketer', 'Маркетолог'), ('admin', 'Администратор')], max_length=255, verbose_name='Должность')),
                ('iin', models.CharField(max_length=12, unique=True, verbose_name='ИИН')),
                ('chat_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Идентификатор чата')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Телеграм')),
                ('rating', models.IntegerField(default=5, verbose_name='Рейтинг')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Так же используйте что бы запретить вход в систему.', verbose_name='Подтверждение')),
            ],
            options={
                'verbose_name': 'сотрудника',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Задача')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено в')),
                ('file', models.FileField(upload_to='')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'задачу',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.employee', unique=True, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'баланс сотрудника',
                'verbose_name_plural': 'Баланс сотрудников',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено в')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('отправлено', 'Отправлено')], default='отправлено', max_length=10, verbose_name='Статус')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.employee', verbose_name='Сотрудник')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'оповещение',
                'verbose_name_plural': 'Оповещения',
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено в')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.employee', verbose_name='Сотрудник')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'историю заданий',
                'verbose_name_plural': 'История заданий',
            },
        ),
        migrations.CreateModel(
            name='WithdrawDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('status', models.CharField(choices=[('новое', 'Новое'), ('подтверждено', 'Подтверждено')], max_length=15, verbose_name='Статус')),
                ('type', models.CharField(choices=[('снятие', 'Снятие'), ('пополнение', 'Пополнение')], max_length=10, verbose_name='Тип транзакции')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено в')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.balance', verbose_name='Баланс')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'транзакцию',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено в')),
                ('status', models.CharField(choices=[('новое', 'Новое'), ('в процессе', 'В процессе'), ('завершено', 'Завершено')], default='новое', max_length=15, verbose_name='Статус')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('priority', models.CharField(choices=[('низкий', 'низкий'), ('средний', 'средний'), ('высокий', 'высокий')], default='низкий', max_length=10, verbose_name='Приоритет')),
                ('checked', models.BooleanField(verbose_name='Проверено')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.employee', verbose_name='Сотрудник')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'задачу сотрудника',
                'verbose_name_plural': 'Задачи сотрудников',
                'unique_together': {('employee', 'task')},
            },
        ),
    ]
