# Generated by Django 5.0.6 on 2024-08-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_employeetask_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='downloads/', verbose_name='Файл'),
        ),
    ]
