# Generated by Django 5.0.6 on 2024-08-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_balance_is_approved_alter_employee_iin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(blank=True, choices=[('junior', 'junior'), ('middle', 'middle'), ('senior', 'senior')], default='junior', max_length=10, verbose_name='Уровень'),
        ),
    ]
