# Generated by Django 5.0.6 on 2024-08-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_employee_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='position',
            field=models.CharField(blank=True, choices=[('copywriter', 'Копирайтер'), ('mobilograph', 'Мобилограф'), ('editor', 'Монтажер'), ('designer', 'Дизайнер'), ('smm', 'СММ'), ('marketer', 'Маркетолог'), ('admin', 'Администратор')], max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
