# Generated by Django 5.0.6 on 2024-08-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='params',
            field=models.JSONField(blank=True, null=True, verbose_name='Доп. параметры'),
        ),
    ]
