# Generated by Django 5.0.6 on 2024-08-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_employeetask_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetask',
            name='params',
        ),
        migrations.AddField(
            model_name='employeetask',
            name='autopass',
            field=models.BooleanField(default=False, verbose_name='Автопередача'),
        ),
    ]
