# Generated by Django 5.0.6 on 2024-08-12 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_alter_employeetask_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.employee', verbose_name='Сотрудник'),
        ),
    ]
